name: pyenv
channels:
  - defaults
  - conda-forge
dependencies:
  - absl-py=2.1.0=py311hca03da5_0
  - aom=3.12.1=ha237518_0
  - astor=0.8.1=py311hca03da5_2
  - astunparse=1.6.3=py_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311h03d0aa3_1
  - brotlicffi=1.2.0.0=py311h50f4ffc_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.11.12=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=py311hca03da5_0
  - contourpy=1.3.3=py311h20e30b6_0
  - cycler=0.12.1=py311hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h982b769_0
  - flatbuffers=24.3.25=h313beb8_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py311haa24f5a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gast=0.6.0=pyhd3eb1b0_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=hc377ac9_1
  - grpcio=1.71.0=py311h313beb8_0
  - h5py=3.15.1=py311h2b875b3_0
  - harfbuzz=10.2.0=he637ebf_1
  - hdf5=1.14.5=hd77251f_2
  - icu=73.1=h313beb8_0
  - idna=3.11=py311hca03da5_0
  - jansson=2.14=h80987f9_1
  - joblib=1.5.2=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - keras=3.6.0=py311hca03da5_0
  - kiwisolver=1.4.9=py311haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcurl=8.17.0=h5bd1c32_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.18=h23cfdf5_2
  - libidn2=2.3.8=h9681e36_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libml_dtypes-headers=0.5.1=hca03da5_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h3e2b118_0
  - libtensorflow_cc=2.18.1=cpu_h13de9f8_0
  - libtiff=4.7.1=h367c460_0
  - libunistring=1.3=h1799b2a_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown=3.8=py311hca03da5_0
  - markdown-it-py=4.0.0=py311hca03da5_1
  - matplotlib=3.10.7=py311hca03da5_0
  - matplotlib-base=3.10.7=py311haa222d5_0
  - mdurl=0.1.2=py311hca03da5_0
  - ml_dtypes=0.4.1=py311h6e33161_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py311h062c92d_0
  - mpich=4.3.2=h3b86219_0
  - namex=0.1.0=py311hca03da5_0
  - ncurses=6.5=h5e97a16_3
  - numexpr=2.14.1=py311h5fbe615_0
  - numpy-base=2.0.1=py311hfbfe69c_1
  - openssl=3.6.0=h5503f6c_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.18.0=py311haeee614_0
  - packaging=25.0=py311hca03da5_1
  - pandas=2.3.3=py311h3f644e9_1
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py311he2d6fe4_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h09dc60e_0
  - protobuf=5.29.3=py311h514c7bf_0
  - pycparser=2.23=py311hca03da5_0
  - pygments=2.19.2=py311hca03da5_0
  - pyparsing=3.2.5=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_1
  - python=3.11.6=h47c9636_0_cpython
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-flatbuffers=24.3.25=py311hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=3_cp311
  - pytz=2025.2=py311hca03da5_0
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h46df422_0
  - requests=2.32.5=py311hca03da5_1
  - rich=14.2.0=py311hca03da5_0
  - scikit-learn=1.8.0=np2py311hf1dd2ad_1
  - scipy=1.16.3=py311h08a1045_0
  - seaborn=0.13.2=py311hca03da5_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=py311hca03da5_0
  - snappy=1.2.2=hada39a4_1
  - sqlite=3.51.0=hab6afd1_0
  - tensorboard=2.18.0=py311hca03da5_0
  - tensorboard-data-server=0.7.0=py311ha6e5c4f_1
  - tensorflow=2.18.1=cpu_py311h18e2dce_0
  - tensorflow-base=2.18.1=cpu_py311h97f355d_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=3.2.0=py311hca03da5_0
  - tf-keras=2.18.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=py311h7eb115d_1
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.4=py311haa24f5a_0
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.1=py311hca03da5_0
  - werkzeug=3.1.3=py311hca03da5_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=2.0.1=py311haa24f5a_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h817c040_0
  - pip:
      - filelock==3.20.1
      - fsspec==2025.12.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.4.0
      - sympy==1.14.0
      - torch==2.9.1
      - torchvision==0.24.1
prefix: /Users/pinacolada/miniconda3/envs/pyenv
